### ISSUE TITLE
64 bits ?

### ISSUE THREAD

**Issue by jm4r7in** [technologiescollege/Blockly-rduino_AIO#1]
Hello,

I'm running Windows 7 64 bits, and I get the message : 

> La version de ce fichier est incompatible avec la version de Windows que vous utilisez [...]

Is it a problem of 32 vs 64 bits ?

Thanks !

**Comment by SebCanet** [comment]
Hi,
it's a Windows problem, new securities added to Windows. No problem, it's compiled in 32 bits so it can be run on any type of Windows, even XP.
Thanks.

**Comment by jm4r7in** [comment]
@SebCanet Je ne comprends pas ton message. Je ne dis pas que c'est un problème de 32 ou 64 bits, je constate juste que le message d'erreur suivant : 

![image](https://cloud.githubusercontent.com/assets/3028663/20395371/fac08c90-ace2-11e6-9507-e34673db95ea.png)

Aurais-tu une idée ?

**Comment by SebCanet** [comment]
Si c'est bien un problème de déclaration de l'exécutable aux services de protection internes à Widnows (UAC et autres joyeusetées). Malheureusement je ne suis pas suffisamment expert en C pour comprendre de quelles déclarations Windows a besoin dans son 'manifest' afin de comprendre que ça tourne sur tout Windows sans auun droit spécifique....
A creuser et boucler, mais là je n'ai pas de VM avec Windows 10, donc à venir un peu plus tard...

Et quand tu cliques sur OK il selance quand même ? Clic droit -> Exécuter en tant qu'administrateur ? ou clic droit -> résoudre les pb de compatibilité ?

**Comment by jm4r7in** [comment]
L'as-tu testé sur Windows ?
Je suis sur Windows 7, pour les autres versions, je ne sais pas.
J'ai testé "Exécuter en tant qu'administrateur" et "résoudre les pb de compatibilité", sans succès... :/

**Comment by SebCanet** [comment]
Je suis sur Windows 8.1 x64, sur Windows 7x32, et je n'ai eu aucun pb.
Le pb vient de W10, Microsoft a rajouté beauoup de paramètres.
Dès que j'ai une VM correcte, je vérifie tout ça.

**Comment by jm4r7in** [comment]
Je suis sur Windows 7x64, donc je ne pense pas que le problème vienne de W10.
